[tool.poetry]
name = "owned_lock"
version = "0.1.0"
description = ""
authors = ["mental <chris@layertwo.info>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
